---
- import_playbook: machineSetup.yml
  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

- import_playbook: toolSetup.yml
  vars:
  #### Select which components to install ####
    conjur_version: 'OSS'
    weavescope_install: 'NO'
    gogs_install: 'NO'
    jenkins_install: 'NO'
    ansible_install: 'NO'
    ansible_pas: 'NO'
    splunk_install: 'YES'
 #### Conjur setup options ####
    conjur_container_name: 'conjur-master'
    conjur_EE_image_name: 'conjur-appliance'
    conjur_network_name: conjur
    conjur_https_port: '443'
    conjur_cli_container_name: 'conjur-cli'
    conjur_cli_image_name: 'cdemo/conjur-cli:latest'
    conjur_account: 'cyberark'
    conjur_admin_password: 'Cyberark1'
    conjur_internal_url: "https://{{ conjur_container_name }}"
    conjur_external_url: "https://{{ ansible_default_ipv4.address }}"
    conjur_audit_volume: "audit"
    conjur_audit_directory: '/var/log/conjur'
    conjur_devops_admin_account: "eva"
    conjur_OSS_image_name: 'cyberark/conjur'
    conjur_OSS_port: '81'
    conjur_OSS_url: "http://{{ ansible_default_ipv4.address }}:{{ conjur_OSS_port }}"
    conjur_OSS_container_name: 'conjur-oss'
    conjur_nginx_image_name: 'cdemo/conjur-nginx:latest'
#### Gogs set up options ####
    gogs_internal_port: '3000'
    gogs_external_port: '10080'
    gogs_container_name: 'gogs'
    gogs_image_version: '0.11.53'
    gogs_image_name: "gogs/gogs:{{ gogs_image_version }}"
    gogs_internal_url: "http://{{ gogs_container_name }}:{{ gogs_internal_port }}"
    gogs_external_url: "http://{{ ansible_default_ipv4.address }}:{{ gogs_external_port }}"
    gogs_account: "{{ conjur_devops_admin_account }}"
    gogs_account_email: 'eva@cyberark.com'
    gogs_account_password: 'Cyberark1'
    gogs_organization: 'Cyberark'
#### Jenkins set up options ####
    jenkins_port: '8080'
    jenkins_url: "http://{{ ansible_default_ipv4.address }}:{{ jenkins_port }}"
    jenkins_image_name: 'conjur_jenkins:latest'
    jenkins_container_name: 'jenkins'
#### AWX set up options ####
    ansible_port: '6060'
    ansible_internal_port: '8052'
    ansible_external_url: "http://{{ ansible_default_ipv4.address }}:{{ ansible_port }}"
    ansible_external_url_login: "{{ ansible_external_url }}/#/login"
    ansible_internal_url: "http://awx_web:{{ ansible_internal_port }}"
    ansible_password: 'Cyberark1'
    ansible_user: "{{ conjur_devops_admin_account }}"
    ansible_organization: 'Cyberark'
    ansible_awx_data_dir: '/ansible/pgdocker'
#### Splunk set up options ####
    splunk_container_name: 'splunk'
    splunk_image_version: '7.2.3'
    splunk_image_name: "{{ splunk_container_name }}/{{ splunk_container_name }}:{{ splunk_image_version }}"
    splunk_hostname: "{{ splunk_container_name }}"
    splunk_http_port: "8088"
    splunk_external_port: "8000"
    splunk_internal_port: "8000"
    splunk_account_password: "{{ gogs_account_password }}"
    splunk_rest_port: "8089"
    splunk_audit_volume: "{{ conjur_audit_volume }}"
    splunk_audit_directory: '/conjur'
    splunk_account: "admin"